### ISSUE TITLE
Don't declare the variable for put the value in the input

### ISSUE THREAD

**Issue by theneonstark** [SatoruSukuna/ecommerce#5]
https://github.com/theTarunsagwal/ecommerce/blob/9b12cc128b90f8189a97a24fbc78120ffd81f1bf/pages/addtocart.php#L219

**Comment by theTarunsagwal** [comment]
yes i know but i think you does not read my code

**Comment by theTarunsagwal** [comment]
At that time, I got the value, so I used it accordingly
